// config.js
require('dotenv').config(); // Load environment variables from .env file

// Hardcoded watchlist from TradingView
const watchlistString =
  'BINANCE:BTCUSDT,BINANCE:MOVRUSDT,BINANCE:ADAUSDT,BINANCE:SOLUSDT,BINANCE:XRPUSDT,BINANCE:AVAXUSDT,BINANCE:LTCUSDT,BINANCE:GALAUSDT,BINANCE:DOGEUSDT,BINANCE:UTKUSDT,BINANCE:IOTAUSDT,BINANCE:ACHUSDT,BINANCE:TKOUSDT,BINANCE:ONDOUSDT,BINANCE:MANAUSDT,BINANCE:MINAUSDT,BINANCE:DIAUSDT,BINANCE:OXTUSDT,BINANCE:XLMUSDT,BINANCE:RVNUSDT,BINANCE:OGNUSDT,BINANCE:AUDIOUSDT,BINANCE:ACAUSDT,BINANCE:SUSDT,BINANCE:ZILUSDT,BINANCE:REQUSDT,OKX:PIUSDT,BINANCE:EOSUSDT, BINANCE:PUNDIXUSDT,BINANCE:ENJUSDT,BINANCE:REZUSDT,BINANCE:API3USDT,BINANCE:ARKMUSDT,BINANCE:BNTUSDT,BINANCE:IOTXUSDT,BINANCE:ARBUSDT,BINANCE:REIUSDT,BINANCE:EDUUSDT,BINANCE:IDEXUSDT,BINANCE:FISUSDT,BINANCE:1INCHUSDT,BINANCE:WOOUSDT,BINANCE:CRVUSDT,BINANCE:VETUSDT,BINANCE:DYDXUSDT,BINANCE:AVAUSDT,BINANCE:TRUUSDT,BINANCE:HFTUSDT,BINANCE:GMTUSDT,BINANCE:KMDUSDT,BINANCE:CELOUSDT,BINANCE:MAVUSDT,BINANCE:SCRTUSDT,BINANCE:FIOUSDT,BINANCE:APEUSDT,BINANCE:TUSDT,BINANCE:ALPHAUSDT,BINANCE:POLUSDT,BINANCE:ATAUSDT,BINANCE:DUSKUSDT,BINANCE:UMAUSDT,BINANCE:HIVEUSDT,BINANCE:MBOXUSDT,BINANCE:WLDUSDT,BINANCE:CFXUSDT,BINANCE:MDTUSDT,BINANCE:YGGUSDT,BINANCE:STXUSDT,BINANCE:BAKEUSDT,BINANCE:ADXUSDT,BINANCE:FLUXUSDT,BINANCE:SANDUSDT,BINANCE:BELUSDT,BINANCE:XTZUSDT,BINANCE:OSMOUSDT,BINANCE:ONGUSDT,BINANCE:GTCUSDT,BINANCE:BLURUSDT,BINANCE:FILUSDT,BINANCE:NEARUSDT,BINANCE:LRCUSDT,BINANCE:POLYXUSDT,BINANCE:ONTUSDT,BINANCE:ZROUSDT,BINANCE:THETAUSDT,BINANCE:FETUSDT,BINANCE:SKLUSDT,BINANCE:PYRUSDT,BINANCE:C98USDT,BINANCE:NEXOUSDT,BINANCE:ARPAUSDT,BINANCE:JOEUSDT,BINANCE:ALICEUSDT,BINANCE:BATUSDT,BINANCE:CTSIUSDT,BINANCE:ASTRUSDT,BINANCE:FLOWUSDT,BINANCE:CHESSUSDT,BINANCE:LOKAUSDT,BINANCE:RAYUSDT,BINANCE:IMXUSDT,BINANCE:RAREUSDT,BINANCE:SNXUSDT,BINANCE:SYSUSDT,BINANCE:LDOUSDT,BINANCE:OPUSDT,BINANCE:KAVAUSDT,BINANCE:SUPERUSDT,BINANCE:ALGOUSDT,BINANCE:CHRUSDT,BINANCE:ROSEUSDT,BINANCE:WANUSDT,BINANCE:SEIUSDT,BINANCE:TWTUSDT,BINANCE:COTIUSDT,BINANCE:SXPUSDT,BINANCE:PHAUSDT,BINANCE:BANDUSDT,BINANCE:CTKUSDT,BINANCE:SUIUSDT,BINANCE:POWRUSDT,BINANCE:HBARUSDT,BINANCE:GRTUSDT,BINANCE:ZRXUSDT,BINANCE:SCUSDT,BINANCE:STORJUSDT,BINANCE:SUNUSDT,BINANCE:BICOUSDT,BINANCE:DFUSDT,BINANCE:WAXPUSDT,BINANCE:MTLUSDT,BINANCE:ZKUSDT,BINANCE:KNCUSDT,BINANCE:ANKRUSDT,BINANCE:RUNEUSDT,BINANCE:PEOPLEUSDT,BINANCE:NTRNUSDT,BINANCE:CVCUSDT,BINANCE:VOXELUSDT,BINANCE:FLMUSDT';

// Split the string by commas and process
const rawSymbols = watchlistString.split(',');
const SYMBOLS = rawSymbols
  .filter((item) => !item.startsWith('###')) // Filter out potential headers
  .map((symbol) => {
    // Remove exchange prefix and convert to lowercase
    return symbol.replace(/^(BINANCE:|OKX:)/, '').toLowerCase();
  })
  .filter((symbol) => symbol.endsWith('usdt')); // Ensure we only have USDT pairs

// Updated intervals for the difference alert
const ALERT_INTERVALS = process.env.ALERT_INTERVALS
  ? process.env.ALERT_INTERVALS.split(',')
  : ['1h', '4h', '1d'];
const CANDLE_LIMIT = parseInt(process.env.CANDLE_LIMIT || '200', 10); // Number of historical candles to fetch and keep

// Add configuration for historical data fetch retries
const MAX_FETCH_RETRIES = parseInt(process.env.MAX_FETCH_RETRIES || '10', 10); // Max retries for fetching historical data
const FETCH_RETRY_DELAY_MS = parseInt(process.env.FETCH_RETRY_DELAY_MS || '5000', 10); // Delay between retries in milliseconds
const ALERT_COOLDOWN_MS = parseInt(
  process.env.ALERT_COOLDOWN_MS || '1800000',
  10
); // 30 minutes cooldown for alerts (updated from 10 mins)

// Telegram Settings
// Telegram Bot Tokens (Environment Variables)
// Ensure these match the variable names in your .env file
const DIFF_ALERT_1H_KEY = process.env.DIFF_ALERT_1H_KEY;
const DIFF_ALERT_4H_KEY = process.env.DIFF_ALERT_4H_KEY;
const DIFF_ALERT_1D_KEY = process.env.DIFF_ALERT_1D_KEY;
const ETH_DIFF_ALERT_KEY = process.env.ETH_TELEGRAM_BOT_TOKEN; // Map the new env var name here
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID;

// Indicator Configurations
// Configuration for RSI(7) with MA(5)
const CONFIG_RSI_7_MA_7 = {
  rsiLength: 7,
  maLength: 5,
  maType: 'VAR', // Assuming 'VAR' is the desired MA type based on your code
};

// Configuration for RSI(21) (MA length/type don't matter for the base RSI value)
const CONFIG_RSI_21 = {
  rsiLength: 21,
  maLength: 21,
  maType: 'VAR',
  percent: 9.0,
  bbMult: 2.0,
};

module.exports = {
  SYMBOLS,
  ALERT_INTERVALS,
  CANDLE_LIMIT,
  ALERT_COOLDOWN_MS,
  CONFIG_RSI_7_MA_7,
  CONFIG_RSI_21,
  TELEGRAM_CHAT_ID,
  DIFF_ALERT_1H_KEY,
  DIFF_ALERT_4H_KEY,
  DIFF_ALERT_1D_KEY,
  ETH_DIFF_ALERT_KEY, // Export the ETH specific key
  // Add new retry configurations
  MAX_FETCH_RETRIES,
  FETCH_RETRY_DELAY_MS,
};
