require('dotenv').config();

// Watchlist symbols (comma-separated, uppercase, will be converted to lowercase and filtered for USDT pairs)
const SYMBOLS_STRING =
  'BINANCE:ETHUSDT,CRYPTOCAP:ETH.D,BINANCE:XRPUSDT,BINANCE:MINAUSDT,BINANCE:ADAUSDT,BINANCE:XLMUSDT,BINANCE:AUDIOUSDT,BINANCE:ONDOUSDT,BINANCE:OGNUSDT,BINANCE:DOGEUSDT,BINANCE:ZILUSDT,BINANCE:GALAUSDT,BINANCE:IOTAUSDT,BINANCE:MANAUSDT,BINANCE:ACHUSDT,BINANCE:RVNUSDT,BINANCE:EOSUSDT,BINANCE:UTKUSDT,BINANCE:MDTUSDT,BINANCE:TKOUSDT,BINANCE:REQUSDT,BINANCE:XTZUSDT,BINANCE:OXTUSDT,BINANCE:BANDUSDT,BINANCE:DIAUSDT,BINANCE:CTSIUSDT,BINANCE:AVAUSDT,BINANCE:CHRUSDT,BINANCE:ATAUSDT,BINANCE:KAVAUSDT,BINANCE:RUNEUSDT,OKX:PIUSDT,BINANCE:PHAUSDT,BINANCE:FETUSDT,BINANCE:RAYUSDT,BINANCE:SEIUSDT,BINANCE:HIVEUSDT,BINANCE:ALGOUSDT,BINANCE:TWTUSDT,BINANCE:HBARUSDT,BINANCE:CRVUSDT,BINANCE:BELUSDT,BINANCE:SUNUSDT,BINANCE:TRUUSDT,BINANCE:SANDUSDT,BINANCE:SUPERUSDT,BINANCE:OPUSDT,BINANCE:API3USDT,BINANCE:ONTUSDT,BINANCE:ARKMUSDT,BINANCE:SXPUSDT,BINANCE:VETUSDT,BINANCE:ARBUSDT,BINANCE:SNXUSDT,BINANCE:LRCUSDT,BINANCE:THETAUSDT,BINANCE:SKLUSDT,BINANCE:STORJUSDT,BINANCE:ROSEUSDT,BINANCE:POLYXUSDT,BINANCE:STXUSDT,BINANCE:NEARUSDT,BINANCE:ZRXUSDT,BINANCE:ENJUSDT,BINANCE:COTIUSDT,BINANCE:GRTUSDT,BINANCE:BAKEUSDT,BINANCE:CFXUSDT,BINANCE:SUIUSDT,BINANCE:LDOUSDT,BINANCE:RAREUSDT,BINANCE:PEOPLEUSDT';

// Remove 'BINANCE:' prefix and convert to lowercase
const SYMBOLS = SYMBOLS_STRING.split(',')
  .map((s) =>
    s
      .trim()
      .replace(/^BINANCE:/, '')
      .toLowerCase()
  )
  .filter((s) => s.endsWith('usdt'));

// Define intervals per symbol
const SYMBOL_INTERVALS = {
  ethusdt: ['1m', '15m', '30m'],
  // Default intervals for all other symbols
  default: ['1m', '1h', '4h', '1d'],
};

// Candle limit for historical data fetching
const CANDLE_LIMIT = 200; // Number of historical candles to fetch

// Configuration for RSI(7) with MA(5)
const CONFIG_RSI_7_MA_7 = {
  rsiLength: 7,
  maLength: 5,
  maType: 'VAR', // Changed from 'SMA' to 'VAR' to match TradingView
};

// Configuration for RSI(21)
const CONFIG_RSI_21 = {
  rsiLength: 21,
  maLength: 5,
  maType: 'VAR', // Changed from 'SMA' to 'VAR' to match TradingView
};

// Telegram Bot Configuration
const TELEGRAM_CHAT_ID = process.env.TELEGRAM_CHAT_ID;
const DIFF_ALERT_1M_KEY = process.env.DIFF_ALERT_1H_KEY;
const DIFF_ALERT_1H_KEY = process.env.DIFF_ALERT_1H_KEY;
const DIFF_ALERT_4H_KEY = process.env.DIFF_ALERT_4H_KEY;
const DIFF_ALERT_1D_KEY = process.env.DIFF_ALERT_1D_KEY;
const ETH_DIFF_ALERT_KEY = process.env.ETH_DIFF_ALERT_KEY; // ETH specific key

// Retry configuration for fetching historical data
const MAX_FETCH_RETRIES = 3; // Maximum number of retries for fetching historical data
const FETCH_RETRY_DELAY_MS = 2000; // Delay between retries in milliseconds

module.exports = {
  SYMBOLS,
  SYMBOL_INTERVALS, // Export the new symbol-specific intervals object
  CANDLE_LIMIT,
  CONFIG_RSI_7_MA_7,
  CONFIG_RSI_21,
  TELEGRAM_CHAT_ID,
  DIFF_ALERT_1H_KEY,
  DIFF_ALERT_4H_KEY,
  DIFF_ALERT_1D_KEY,
  ETH_DIFF_ALERT_KEY,
  MAX_FETCH_RETRIES,
  FETCH_RETRY_DELAY_MS,
  DIFF_ALERT_1M_KEY
};
